window.LANGUAGES = {
  "en": {
    "native": "English",
    "name": "English",
    "dir": "ltr",
    "title": "RESIDENT MAINTENANCE ISSUE REPORT",
    "intro": null,
    "labels": {
      "name": "Name",
      "room": "Room Number",
      "building": "Building Number",
      "floor": "Floor Number",
      "location": "Fault Location",
      "category": "Fault Category",
      "description": "Fault Description",
      "photo": "Photo of Fault",
      "reported": "Date & Time Reported"
    },
    "locations": [
      "Room",
      "Bathroom",
      "Kitchen",
      "Corridor",
      "Common Area",
      "External",
      "Other"
    ],
    "categories": [
      "Electrical",
      "Plumbing",
      "HVAC",
      "Carpentry",
      "Appliance",
      "Cleaning",
      "Safety",
      "Other"
    ],
    "confirmation": "Thank you. Your maintenance issue has been reported successfully. Please keep your reference number for follow-up.",
    "ui": {
      "brand": "Resident services",
      "badge": "MAINTENANCE",
      "change": "Change language",
      "details": "Your details",
      "issue": "About the issue",
      "attachments": "Photos & videos",
      "upload": "Photos or videos of the fault (optional)",
      "uploadHelp": "Up to 3 files; 10 MB each, 25 MB total. JPG, PNG, WebP, HEIC, HEIF, MP4, MOV or WebM.",
      "automatic": "Date and time will be recorded automatically on submission.",
      "required": "* Required fields",
      "submit": "Submit report",
      "choose": "Choose an option",
      "sending": "Sending…",
      "success": "Report received",
      "reference": "Reference number",
      "another": "Report another issue",
      "remove": "Remove",
      "invalid": "Please complete all required fields.",
      "fileError": "Select up to 3 supported files, 10 MB each and 25 MB total.",
      "setup": "The connection is not set up yet. You can review this form, but reports cannot be sent.",
      "network": "We could not confirm submission. Keep this page open and retry with the same details.",
      "security": "Please complete the security check.",
      "footer": "Resident maintenance · One place to report an issue"
    }
  },
  "ar": {
    "native": "العربية",
    "name": "Arabic",
    "dir": "rtl",
    "title": "نموذج الإبلاغ عن أعطال الصيانة للسكان",
    "intro": null,
    "labels": {
      "name": "الاسم",
      "room": "رقم الغرفة",
      "building": "رقم المبنى",
      "floor": "رقم الطابق",
      "location": "موقع العطل",
      "category": "فئة العطل",
      "description": "وصف العطل",
      "photo": "صورة للعطل",
      "reported": "تاريخ ووقت الإبلاغ"
    },
    "locations": [
      "الغرفة",
      "الحمام",
      "المطبخ",
      "الممر",
      "منطقة مشتركة",
      "خارجية",
      "أخرى"
    ],
    "categories": [
      "كهرباء",
      "سباكة",
      "تكييف",
      "نجارة",
      "أجهزة",
      "نظافة",
      "سلامة",
      "أخرى"
    ],
    "confirmation": "شكرًا لك. تم تسجيل بلاغ الصيانة بنجاح. يرجى الاحتفاظ بالرقم المرجعي للمتابعة.",
    "ui": {
      "brand": "خدمات السكان",
      "badge": "الصيانة",
      "change": "تغيير اللغة",
      "details": "بياناتك",
      "issue": "تفاصيل العطل",
      "attachments": "الصور والفيديو",
      "upload": "صور أو فيديو للعطل (اختياري)",
      "uploadHelp": "حتى 3 ملفات؛ 10 ميجابايت لكل ملف و25 ميجابايت إجمالًا. JPG، PNG، WebP، HEIC، HEIF، MP4، MOV أو WebM.",
      "automatic": "سيتم تسجيل التاريخ والوقت تلقائيًا عند الإرسال.",
      "required": "* حقول مطلوبة",
      "submit": "إرسال البلاغ",
      "choose": "اختر خيارًا",
      "sending": "جارٍ الإرسال…",
      "success": "تم استلام البلاغ",
      "reference": "الرقم المرجعي",
      "another": "الإبلاغ عن عطل آخر",
      "remove": "إزالة",
      "invalid": "يرجى تعبئة جميع الحقول المطلوبة.",
      "fileError": "اختر حتى 3 ملفات مدعومة، بحد أقصى 10 ميجابايت لكل ملف و25 ميجابايت إجمالًا.",
      "setup": "لم يتم إعداد الاتصال بعد. يمكنك مراجعة النموذج، لكن لا يمكن إرسال البلاغات حاليًا.",
      "network": "تعذر تأكيد الإرسال. أبقِ الصفحة مفتوحة وأعد المحاولة بنفس البيانات.",
      "security": "يرجى إكمال التحقق الأمني.",
      "footer": "صيانة السكان · مكان واحد للإبلاغ عن الأعطال"
    }
  },
  "hi": {
    "native": "हिन्दी",
    "name": "Hindi",
    "dir": "ltr",
    "title": "निवासी रखरखाव समस्या रिपोर्ट",
    "intro": null,
    "labels": {
      "name": "नाम",
      "room": "कमरा नंबर",
      "building": "बिल्डिंग नंबर",
      "floor": "मंज़िल नंबर",
      "location": "समस्या का स्थान",
      "category": "समस्या की श्रेणी",
      "description": "समस्या का विवरण",
      "photo": "समस्या की फोटो",
      "reported": "रिपोर्ट की तारीख और समय"
    },
    "locations": [
      "कमरा",
      "बाथरूम",
      "रसोई",
      "कॉरिडोर",
      "साझा क्षेत्र",
      "बाहरी क्षेत्र",
      "अन्य"
    ],
    "categories": [
      "बिजली",
      "प्लंबिंग",
      "HVAC",
      "बढ़ईगीरी",
      "उपकरण",
      "सफाई",
      "सुरक्षा",
      "अन्य"
    ],
    "confirmation": "धन्यवाद। आपकी रखरखाव समस्या सफलतापूर्वक दर्ज कर ली गई है। कृपया फॉलो-अप के लिए अपना संदर्भ नंबर सुरक्षित रखें।",
    "ui": {
      "brand": "निवासी सेवाएँ",
      "badge": "रखरखाव",
      "change": "भाषा बदलें",
      "details": "आपकी जानकारी",
      "issue": "समस्या की जानकारी",
      "attachments": "फ़ोटो और वीडियो",
      "upload": "समस्या की फ़ोटो या वीडियो (वैकल्पिक)",
      "uploadHelp": "अधिकतम 3 फ़ाइलें; प्रत्येक 10 MB और कुल 25 MB। JPG, PNG, WebP, HEIC, HEIF, MP4, MOV या WebM।",
      "automatic": "जमा करने पर तारीख और समय अपने आप दर्ज होंगे।",
      "required": "* ज़रूरी जानकारी",
      "submit": "शिकायत जमा करें",
      "choose": "एक विकल्प चुनें",
      "sending": "भेजा जा रहा है…",
      "success": "शिकायत प्राप्त हुई",
      "reference": "संदर्भ नंबर",
      "another": "दूसरी शिकायत दर्ज करें",
      "remove": "हटाएँ",
      "invalid": "कृपया सभी ज़रूरी जानकारी भरें।",
      "fileError": "अधिकतम 3 समर्थित फ़ाइलें चुनें, प्रत्येक 10 MB और कुल 25 MB तक।",
      "setup": "कनेक्शन अभी सेट नहीं हुआ है। आप फ़ॉर्म देख सकते हैं, लेकिन शिकायत अभी भेजी नहीं जा सकती।",
      "network": "शिकायत जमा होने की पुष्टि नहीं हुई। यह पेज खुला रखें और उसी जानकारी के साथ फिर कोशिश करें।",
      "security": "कृपया सुरक्षा जाँच पूरी करें।",
      "footer": "निवासी रखरखाव · समस्या की रिपोर्ट करने का एक स्थान"
    }
  },
  "ur": {
    "native": "اردو",
    "name": "Urdu",
    "dir": "rtl",
    "title": "رہائشی مینٹیننس مسئلہ رپورٹ",
    "intro": null,
    "labels": {
      "name": "نام",
      "room": "کمرہ نمبر",
      "building": "عمارت نمبر",
      "floor": "منزل نمبر",
      "location": "خرابی کا مقام",
      "category": "خرابی کی قسم",
      "description": "خرابی کی تفصیل",
      "photo": "خرابی کی تصویر",
      "reported": "رپورٹ کی تاریخ اور وقت"
    },
    "locations": [
      "کمرہ",
      "باتھ روم",
      "کچن",
      "راہداری",
      "مشترکہ جگہ",
      "بیرونی جگہ",
      "دیگر"
    ],
    "categories": [
      "بجلی",
      "پلمبنگ",
      "HVAC",
      "کارپینٹری",
      "آلات",
      "صفائی",
      "سیفٹی",
      "دیگر"
    ],
    "confirmation": "شکریہ۔ آپ کی مینٹیننس شکایت کامیابی سے درج ہو گئی ہے۔ براہ کرم فالو اپ کے لیے اپنا ریفرنس نمبر محفوظ رکھیں۔",
    "ui": {
      "brand": "رہائشی خدمات",
      "badge": "مینٹیننس",
      "change": "زبان تبدیل کریں",
      "details": "آپ کی معلومات",
      "issue": "خرابی کی معلومات",
      "attachments": "تصاویر اور ویڈیو",
      "upload": "خرابی کی تصاویر یا ویڈیو (اختیاری)",
      "uploadHelp": "زیادہ سے زیادہ 3 فائلیں؛ ہر فائل 10 MB اور کل 25 MB۔ JPG، PNG، WebP، HEIC، HEIF، MP4، MOV یا WebM۔",
      "automatic": "جمع کرانے پر تاریخ اور وقت خودکار طور پر درج ہوں گے۔",
      "required": "* ضروری معلومات",
      "submit": "شکایت جمع کریں",
      "choose": "ایک اختیار منتخب کریں",
      "sending": "بھیجا جا رہا ہے…",
      "success": "شکایت موصول ہو گئی",
      "reference": "ریفرنس نمبر",
      "another": "ایک اور شکایت درج کریں",
      "remove": "ہٹائیں",
      "invalid": "براہ کرم تمام ضروری معلومات درج کریں۔",
      "fileError": "زیادہ سے زیادہ 3 معاون فائلیں منتخب کریں، ہر فائل 10 MB اور کل 25 MB تک۔",
      "setup": "کنکشن ابھی ترتیب نہیں دیا گیا۔ آپ فارم دیکھ سکتے ہیں لیکن ابھی شکایت نہیں بھیج سکتے۔",
      "network": "شکایت جمع ہونے کی تصدیق نہیں ہو سکی۔ صفحہ کھلا رکھیں اور اسی معلومات کے ساتھ دوبارہ کوشش کریں۔",
      "security": "براہ کرم سیکیورٹی چیک مکمل کریں۔",
      "footer": "رہائشی مینٹیننس · خرابی کی اطلاع دینے کے لیے ایک جگہ"
    }
  },
  "tl": {
    "native": "Filipino / Tagalog",
    "name": "Tagalog",
    "dir": "ltr",
    "title": "ULAT NG ISYU SA MAINTENANCE NG RESIDENTE",
    "intro": null,
    "labels": {
      "name": "Pangalan",
      "room": "Numero ng Kuwarto",
      "building": "Numero ng Gusali",
      "floor": "Numero ng Palapag",
      "location": "Lokasyon ng Sira",
      "category": "Kategorya ng Sira",
      "description": "Paglalarawan ng Sira",
      "photo": "Larawan ng Sira",
      "reported": "Petsa at Oras ng Pag-uulat"
    },
    "locations": [
      "Kuwarto",
      "Banyo",
      "Kusina",
      "Pasilyo",
      "Common Area",
      "Panlabas",
      "Iba pa"
    ],
    "categories": [
      "Electrical",
      "Plumbing",
      "HVAC",
      "Carpentry",
      "Appliance",
      "Cleaning",
      "Safety",
      "Iba pa"
    ],
    "confirmation": "Salamat. Matagumpay na naitala ang iyong maintenance issue. Pakitago ang iyong reference number para sa follow-up.",
    "ui": {
      "brand": "Mga serbisyo para sa residente",
      "badge": "MAINTENANCE",
      "change": "Palitan ang wika",
      "details": "Iyong mga detalye",
      "issue": "Tungkol sa problema",
      "attachments": "Mga larawan at video",
      "upload": "Mga larawan o video ng sira (opsyonal)",
      "uploadHelp": "Hanggang 3 file; 10 MB bawat isa at 25 MB sa kabuuan. JPG, PNG, WebP, HEIC, HEIF, MP4, MOV o WebM.",
      "automatic": "Awtomatikong itatala ang petsa at oras kapag isinumite.",
      "required": "* Mga kinakailangang sagot",
      "submit": "Isumite ang ulat",
      "choose": "Pumili ng opsyon",
      "sending": "Ipinapadala…",
      "success": "Natanggap ang ulat",
      "reference": "Reference number",
      "another": "Mag-ulat ng isa pang isyu",
      "remove": "Alisin",
      "invalid": "Mangyaring sagutan ang lahat ng kinakailangang field.",
      "fileError": "Pumili ng hanggang 3 suportadong file, 10 MB bawat isa at 25 MB sa kabuuan.",
      "setup": "Hindi pa naka-set up ang koneksyon. Maaari mong tingnan ang form ngunit hindi pa makapagpadala ng ulat.",
      "network": "Hindi makumpirma ang pagsusumite. Panatilihing bukas ang pahina at subukang muli gamit ang parehong detalye.",
      "security": "Mangyaring kumpletuhin ang security check.",
      "footer": "Maintenance ng residente · Isang lugar para mag-ulat ng problema"
    }
  }
};
